# Generated by Django 5.0.1 on 2024-02-05 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('صباحي', 'صباحي'), ('مسائي', 'مسائي')], default=('صباحي', 'صباحي'), max_length=50)),
            ],
            options={
                'unique_together': {('date', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ShiftDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended', models.BooleanField(default=False, null=True)),
                ('started', models.BooleanField(default=False, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_detail', to='gates.gate')),
                ('mainShift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='shift.shift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mainShift', 'user')},
            },
        ),
    ]
