# Generated by Django 5.0.1 on 2024-02-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_gate_open_in_gate_open_out_gate_pc_ip_and_more'),
        ('shift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shiftdetail',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_detail', to='gates.gate'),
        ),
        migrations.RemoveField(
            model_name='shiftdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='shiftdetail',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='shift_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
