# Generated by Django 5.0.1 on 2024-02-06 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftdetail',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='shift_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shiftdetail',
            name='user',
        ),
    ]
