# Generated by Django 5.0.1 on 2024-02-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_shiftdetail_unique_together_shiftdetail_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftdetail',
            old_name='users',
            new_name='user',
        ),
    ]
