# Generated by Django 5.0.1 on 2024-02-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_alter_gate_ip_alter_gate_name'),
        ('shift', '0003_rename_users_shiftdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_detail', to='gates.gate'),
        ),
    ]
