# Generated by Django 4.2.9 on 2024-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_alter_shiftdetail_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdetail',
            name='started',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
