# Generated by Django 5.0.1 on 2024-02-09 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_alter_shiftdetail_machine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='shift_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
