# Generated by Django 5.0.1 on 2024-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
