# Generated by Django 5.0.1 on 2024-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='open_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gate',
            name='open_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gate',
            name='pc_ip',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='cam_in_ip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='cam_out_ip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
