# Generated by Django 5.0.1 on 2024-02-22 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('cash', '0002_remove_cashdetail_cash_remove_cashdetail_cashier_and_more'),
        ('shift', '0002_alter_shiftdetail_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='isExcept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='isSubscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='cash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cash.cash'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='cashire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_session', to='card.category'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='image_in',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='image_out',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='lost_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='shift_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_in', to='shift.shiftdetail'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='shift_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_out', to='shift.shiftdetail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='intial_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='intial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_session', to='card.parkingcard'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='card.parkingcard'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_payment', to='card.parkingcard')),
                ('subscription_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='card.subscriptionpackage')),
            ],
        ),
    ]
