# Generated by Django 5.0.1 on 2024-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_subscription_card_parkingcard_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
