# Generated by Django 5.0.1 on 2024-02-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_subscriptionpackage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingcard',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='card',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='card.parkingcard'),
            preserve_default=False,
        ),
    ]
