# Generated by Django 5.0.1 on 2024-02-09 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_subscription_card_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parking_session', to='card.category'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_session', to='card.parkingcard'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
