# Generated by Django 5.0.1 on 2024-02-09 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_parkingsession_category_alter_parkingsession_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_session', to='card.category'),
        ),
    ]
