# Generated by Django 5.0.1 on 2024-02-11 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_parkingsession_category'),
        ('cash', '0003_remove_cashdetail_cash_remove_cashdetail_cashier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='cash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cash.cash'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='cashire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
