# Generated by Django 5.0.1 on 2024-02-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_parkingsession_cash_parkingsession_cashire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingsession',
            old_name='image',
            new_name='image_in',
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='image_out',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
