# Generated by Django 5.0.1 on 2024-02-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_rename_image_parkingsession_image_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
