# Generated by Django 5.0.1 on 2024-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_parkingsession_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='image_in',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='image_out',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
