# Generated by Django 5.0.1 on 2024-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_parkingsession_image_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='lost_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
