# Generated by Django 5.0.1 on 2024-02-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_parkingsession_lost_card_parkingsession_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_session', to='card.parkingcard'),
        ),
    ]
