# Generated by Django 5.0.1 on 2024-02-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_parkingsession_card'),
        ('shift', '0005_alter_shiftdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='shift_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_in', to='shift.shiftdetail'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='shift_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_out', to='shift.shiftdetail'),
        ),
    ]
