# Generated by Django 5.0.1 on 2024-02-05 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gates', '0001_initial'),
        ('shift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('money_per_hour', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash', to='shift.shiftdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CashDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=50, null=True)),
                ('time_in', models.DateTimeField(null=True)),
                ('time_out', models.DateTimeField()),
                ('product', models.CharField(max_length=50)),
                ('product_cost', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.PositiveIntegerField()),
                ('offer', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('card_lost', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cash.cash')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_detail', to=settings.AUTH_USER_MODEL)),
                ('machine_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_in', to='gates.gate')),
                ('machine_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_out', to='gates.gate')),
            ],
        ),
    ]
