# Generated by Django 4.2.9 on 2024-01-31 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift', '0001_initial'),
        ('acces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash', to='shift.shiftdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('money_per_hour', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=50, null=True)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('product', models.CharField(max_length=50)),
                ('product_cost', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.PositiveIntegerField()),
                ('offer', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('card_lost', models.BooleanField(default=False)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cash.cash')),
                ('machine_in', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_in', to='acces.machines')),
                ('machine_out', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_out', to='acces.machines')),
            ],
        ),
    ]
