# Generated by Django 5.0.1 on 2024-02-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('gates', '0002_alter_gate_ip_alter_gate_name'),
        ('shift', '0003_rename_users_shiftdetail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='shift.shiftdetail'),
        ),
        migrations.AlterField(
            model_name='cashdetail',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashdetail',
            name='machine_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_in', to='gates.gate'),
        ),
        migrations.AlterField(
            model_name='cashdetail',
            name='machine_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_out', to='gates.gate'),
        ),
    ]
