# Generated by Django 5.0.1 on 2024-02-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('shift', '0002_alter_shiftdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdetail',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='cashdetail',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='cashdetail',
            name='machine_in',
        ),
        migrations.RemoveField(
            model_name='cashdetail',
            name='machine_out',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='cash',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='shift.shiftdetail'),
        ),
        migrations.DeleteModel(
            name='CashDetail',
        ),
    ]
