# Generated by Django 4.2.9 on 2024-01-31 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0003_machines_place'),
        ('cash', '0002_cash_start_cashdetail_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdetail',
            name='machine_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_in', to='acces.machines'),
        ),
        migrations.AlterField(
            model_name='cashdetail',
            name='machine_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_out', to='acces.machines'),
        ),
        migrations.AlterField(
            model_name='cashdetail',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
    ]
