# Generated by Django 5.0.1 on 2024-02-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cash_shift_alter_cashdetail_cashier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdetail',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='cashdetail',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='cashdetail',
            name='machine_in',
        ),
        migrations.RemoveField(
            model_name='cashdetail',
            name='machine_out',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='CashDetail',
        ),
    ]
