# Generated by Django 4.2.9 on 2024-02-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_alter_cashdetail_machine_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdetail',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
