# Generated by Django 4.2.9 on 2024-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.PositiveIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time', null=True)),
                ('card_no', models.PositiveIntegerField(db_column='card_no', null=True)),
                ('state', models.CharField(choices=[(0, 'in'), (1, 'out'), (2, 'no action')], db_column='state', max_length=50, null=True)),
            ],
            options={
                'db_table': '[access].[dbo].[acc_monitor_log]',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.PositiveIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='MachineAlias', max_length=50, null=True)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=50, null=True)),
            ],
            options={
                'db_table': '[access].[dbo].[Machines]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.PositiveIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='MachineAlias', max_length=50, null=True)),
                ('number_of_car', models.PositiveIntegerField(db_column='car_number')),
            ],
            options={
                'db_table': '[access].[hazem].[Places]',
            },
        ),
    ]
