# Generated by Django 4.2.9 on 2024-01-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={},
        ),
    ]
