# Generated by Django 5.0.1 on 2024-02-15 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0002_remove_moneytransaction_type'),
        ('shift', '0005_alter_shiftdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransaction',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='shift.shiftdetail'),
            preserve_default=False,
        ),
    ]
