# Generated by Django 5.0.1 on 2024-02-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0003_moneytransaction_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytransaction',
            name='shift',
        ),
    ]
