# Generated by Django 4.2.9 on 2024-02-01 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0006_moneytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
