# Generated by Django 4.2.9 on 2024-02-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0007_moneytransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='cam_ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
