# Generated by Django 5.0.1 on 2024-02-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0008_machines_cam_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='number_of_car',
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='type',
            field=models.CharField(choices=[(0, 'to-admin'), (1, 'to-next-shift')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machines',
            name='Place',
            field=models.ForeignKey(db_column='Place_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machine', to='acces.place'),
        ),
    ]
